import "./globals.css";
import NavBar from "@/components/NavBar";
import { Providers } from "@/components/Providers"; 
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "GreeNet",
  description: "Generated by create next app",
  icons:"/logo.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <Providers>
          <NavBar />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
