import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import SideBar from "@/components/Dashboard/Sidebar";

export const metadata: Metadata = {
	title: "GreeNet",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className=" flex flex-col">
				<NavBar />

				<div className="flex flex-grow">
					<SideBar />
				</div>
				<div className="flex-grow ml-[20%] p-6 overflow-y-auto">
					{children}
				</div>
			</body>
		</html>
	);
}
